services:
  game-finder:
    # PROD
    image: ghcr.io/guevaran/game-finder:latest
    # DEV
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # image: game-finder:latest

    container_name: game-finder
    restart: unless-stopped
    ports:
      - 3003:3000
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    # environment:
    #   - IGDB_API_BASE_URL=${IGDB_API_BASE_URL}
    #   - IGDB_TWITCH_AUTH_URL=${IGDB_TWITCH_AUTH_URL}
    #   - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
    #   - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
